# Generated by Django 5.1.5 on 2025-02-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.URLField(),
        ),
    ]
