# Generated by Django 5.1.5 on 2025-02-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.TextField(max_length=100),
        ),
    ]
