# Generated by Django 5.1.5 on 2025-02-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='eu_size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='uk_size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='us_size',
            field=models.CharField(max_length=20),
        ),
    ]
