# Generated by Django 5.1.5 on 2025-02-01 15:59

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_productvariant_image_productvariant_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to=Main.models.upload_to_product_img),
        ),
    ]
