# Generated by Django 5.1.5 on 2025-02-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_productimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
