# Generated by Django 5.1.5 on 2025-02-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_rename_image_url_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Main.product'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('35/5/34.5', 'EUR : 35.0 / US : 5.0 / UK : 34.5'), ('35.5/5.5/35', 'EUR : 35.5 / US : 5.5 / UK : 35.0'), ('36/6/35.5', 'EUR : 36 / US : 6 / UK : 35.5'), ('37/6.5/36.5', 'EUR : 37 / US : 6.5 / UK : 36.5'), ('37.5/7/37', 'EUR : 37.5 / US : 7 / UK : 37'), ('38/7.5/37.5', 'EUR : 38 / US : 7.5 / UK : 37.5'), ('38.5/8/38', 'EUR : 38.5 / US : 8 / UK : 38'), ('39/8.5/38.5', 'EUR : 39 / US : 8.5 / UK : 38.5'), ('39.5/9/39', 'EUR : 39.5 / US : 9 / UK : 39'), ('40/9.5/39.5', 'EUR : 40 / US : 9.5 / UK : 39.5')], default='1', max_length=30),
        ),
    ]
