# Generated by Django 5.1.5 on 2025-02-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_size_remove_productvariant_size_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
