# Generated by Django 5.1.5 on 2025-02-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite', '0001_initial'),
        ('Main', '0014_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='item',
        ),
        migrations.CreateModel(
            name='FavoriteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Favorite.favorite')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.productvariant')),
            ],
        ),
    ]
