# Generated by Django 5.1.5 on 2025-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite', '0002_remove_favorite_item_favoriteitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitems',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
