# Generated by Django 5.1.5 on 2025-02-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite', '0003_favoriteitems_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitems',
            name='date_added',
        ),
    ]
