# Generated by Django 5.1.5 on 2025-02-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite', '0004_remove_favoriteitems_date_added'),
        ('Main', '0014_alter_product_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteItems',
            new_name='FavoriteItem',
        ),
    ]
