# Generated by Django 5.1.5 on 2025-05-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite', '0005_rename_favoriteitems_favoriteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteitems', to='Favorite.favorite'),
        ),
    ]
