# Generated by Django 5.1.5 on 2025-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
