# Generated by Django 5.1.5 on 2025-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_cartitem_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_added',
            field=models.BooleanField(),
        ),
    ]
