# Generated by Django 5.1.5 on 2025-02-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_added',
        ),
    ]
