# Generated by Django 5.1.5 on 2025-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='mailingdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
