# Generated by Django 5.1.5 on 2025-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_orderitem_quantity_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default='2025-02-23'),
            preserve_default=False,
        ),
    ]
