# Generated by Django 5.1.5 on 2025-02-22 15:53
import Orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_orderitem_quantity_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=Orders.models.default_delivery_date),
        ),
    ]
