# Generated by Django 5.1.5 on 2025-02-22 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 21, 40, 20, 627110)),
        ),
    ]
