# Generated by Django 5.1.5 on 2025-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_city',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_district',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_email',
            field=models.EmailField(default='1', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.DeleteModel(
            name='MailingDetails',
        ),
    ]
