# Generated by Django 5.1.5 on 2025-02-22 15:57

import Orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=Orders.models.default_delivery_date),
        ),
    ]
