# Generated by Django 5.1.5 on 2025-05-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_remove_order_shipping_address_order_receiver_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(max_length=10),
        ),
    ]
